### ISSUE TITLE
Windows Platform Implementation version matching

### ISSUE THREAD

**Issue by wbaleson** [jcapellman/WAVE#9]
Version = ParseVersion(subKey.GetValue("Version")?.ToString(),
                                    subKey.GetValue("DisplayVersion")?.ToString(), subKey.GetValue("VersionMajor")?.ToString(),
                                    subKey.GetValue("VersionMinor")?.ToString()),

I believe we should be matching first on displayversion, then on versionmajor+versionminor, then on version. Most applications we've seen look like this:
![image](https://user-images.githubusercontent.com/6403900/132722230-18b8f876-8d81-4429-a5c5-c929962ae44b.png)

Send you the credentials for the da-dev implementation over slack

**Comment by jcapellman** [comment]
Resolved
